sudo: false

language: node_js

env:
  - CXX="g++-4.8"

node_js:
  - "6"
  - "8"
  - "9"
  - "10"

cache:
  yarn: true
  directories:
    - node_modules/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
